node_env: "development"
secret_service: 'MediaServiceSecret'
access_secret: "your-access-jwt-secret-here"
name_service: "MediaService"
port_grpc: 40063
host_grpc: "localhost"
interval_check: "20s"
timeout_check: "5s"
url_db: "postgres://postgres:123456@localhost:5432/media_service_db?sslmode=disable"

storage_local:
    upload_dir: "C:/uploads"

db_cache:
    addr: 'localhost:6379'
    db: 1
    password: ''
    max_idle: 10
    max_active: 100
    idle_timeout: 240
    network: 'tcp'

permission_service_addr: 'localhost:50051'

grpc_clients:
    - Name: 'PermissionService'
      ServerAddress: 'localhost:50051'
      MaxRetries: 3
      Time: 20
      Timeout: 15
      PermitWithoutStream: true
      SecretInternal: 'PermissionServiceSecret'

# Queue configuration for async processing
queue:
  addr: "localhost:6379"
  db: 1
  password: ""
  network: "tcp"
  timeout: 30
  tls: false
  retry: 3
