node_env: "development"
name_service: "MediaService"
port_grpc: 50053
host_grpc: "localhost"
interval_check: "20s"
timeout_check: "5s"

url_db: "postgres://postgres:123456@localhost:5432/media_service_db?sslmode=disable"

storage_local:
    upload_dir: "C:/uploads"

# gRPC client configurations
# grpc_clients:
#   auth_service:
#     addr: "localhost:8081"
#     timeout: 30s

# Queue configuration for async processing
queue:
  addr: "localhost:6379"
  db: 1
  password: ""
  network: "tcp"
  timeout: 30
  tls: false
  retry: 3
