// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/media/v1/media.proto

package media

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size             int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Url              string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	MimeType         string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Type             string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Width            int32                  `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	Duration         int32                  `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`
	ProcessingStatus string                 `protobuf:"bytes,11,opt,name=processing_status,json=processingStatus,proto3" json:"processing_status,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_media_v1_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Media) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Media) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Media) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Media) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Media) GetProcessingStatus() string {
	if x != nil {
		return x.ProcessingStatus
	}
	return ""
}

func (x *Media) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Media) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// MediaVariant message
type MediaVariant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaId   string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Type      string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Size      string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Url       string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	FileSize  int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Width     int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height    int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	Quality   int32                  `protobuf:"varint,9,opt,name=quality,proto3" json:"quality,omitempty"`
	Format    string                 `protobuf:"bytes,10,opt,name=format,proto3" json:"format,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *MediaVariant) Reset() {
	*x = MediaVariant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_media_v1_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaVariant) ProtoMessage() {}

func (x *MediaVariant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaVariant.ProtoReflect.Descriptor instead.
func (*MediaVariant) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaVariant) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaVariant) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaVariant) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *MediaVariant) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaVariant) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MediaVariant) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaVariant) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaVariant) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *MediaVariant) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *MediaVariant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_media_v1_media_proto protoreflect.FileDescriptor

var file_proto_media_v1_media_proto_rawDesc = []byte{}

var (
	file_proto_media_v1_media_proto_rawDescOnce sync.Once
	file_proto_media_v1_media_proto_rawDescData = file_proto_media_v1_media_proto_rawDesc
)

func file_proto_media_v1_media_proto_rawDescGZIP() []byte {
	file_proto_media_v1_media_proto_rawDescOnce.Do(func() {
		file_proto_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_media_v1_media_proto_rawDescData)
	})
	return file_proto_media_v1_media_proto_rawDescData
}

var file_proto_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_media_v1_media_proto_goTypes = []interface{}{
	(*Media)(nil),                 // 0: media.v1.Media
	(*MediaVariant)(nil),          // 1: media.v1.MediaVariant
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_media_v1_media_proto_depIdxs = []int32{
	2, // 0: media.v1.Media.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: media.v1.Media.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: media.v1.MediaVariant.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_media_v1_media_proto_init() }
func file_proto_media_v1_media_proto_init() {
	if File_proto_media_v1_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_media_v1_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_media_v1_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaVariant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_media_v1_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_v1_media_proto_goTypes,
		DependencyIndexes: file_proto_media_v1_media_proto_depIdxs,
		MessageInfos:      file_proto_media_v1_media_proto_msgTypes,
	}.Build()
	File_proto_media_v1_media_proto = out.File
	file_proto_media_v1_media_proto_rawDesc = nil
	file_proto_media_v1_media_proto_goTypes = nil
	file_proto_media_v1_media_proto_depIdxs = nil
}
